// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var SimpleMap$MyProjectName = require("./SimpleMap.bs.js");

var component = ReasonReact.statelessComponent("App");

var geographyStyle = {
  default: {
    outline: "none",
    fill: "#ECEFF1",
    stroke: "#607D8B",
    strokeWidth: "0.75"
  },
  hover: {
    outline: "none",
    fill: "#607D8B",
    stroke: "#607D8B",
    strokeWidth: "0.75"
  },
  pressed: {
    outline: "none",
    fill: "#FF5722",
    stroke: "#607D8B",
    strokeWidth: "0.75"
  }
};

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, SimpleMap$MyProjectName.ComposableMap[/* make */0]({
                              scale: 205,
                              rotation: /* array */[
                                -11,
                                0,
                                0
                              ]
                            }, 980, 551, /* array */[ReasonReact.element(/* None */0, /* None */0, SimpleMap$MyProjectName.Geographies[/* make */0]("world-50m.json", /* array */[(function (geographies, projection) {
                                            return $$Array.mapi((function (index, geography) {
                                                          return ReasonReact.element(/* Some */[String(index)], /* None */0, SimpleMap$MyProjectName.Geography[/* make */0](geography, projection, geographyStyle, /* array */[]));
                                                        }), geographies);
                                          })]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.geographyStyle = geographyStyle;
exports.make = make;
/* component Not a pure module */
