// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSimpleMaps = require("react-simple-maps");

function make(projectionConfig, width, height, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.ComposableMap, {
              projectionConfig: projectionConfig,
              width: width,
              height: height
            }, children);
}

var ComposableMap = /* module */[/* make */make];

function make$1(geography, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.Geographies, {
              geography: geography
            }, children);
}

var Geographies = /* module */[/* make */make$1];

function make$2(geography, projection, style, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.Geography, {
              geography: geography,
              projection: projection,
              style: style
            }, children);
}

var Geography = /* module */[/* make */make$2];

exports.ComposableMap = ComposableMap;
exports.Geographies = Geographies;
exports.Geography = Geography;
/* ReasonReact Not a pure module */
